### ISSUE TITLE
Is there a way to update trackers(ask tracker for more peers)?

### ISSUE THREAD

**Issue by TTTPOB** [rmartin16/qbittorrent-api#1]
as the title says

**Comment by rmartin16** [comment]
I think the [reannounce torrents endpoint](https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#reannounce-torrents) provides this.

```python
client = Client(...)
client.torrents_reannounce(hashes='...')
```

`hashes='all'` should work.

**Comment by TTTPOB** [comment]
It works like a charm, thanks for your work!

________________________________
发件人: rmartin16 <notifications@github.com>
发送时间: Friday, September 27, 2019 10:35:55 PM
收件人: rmartin16/qbittorrent-api <qbittorrent-api@noreply.github.com>
抄送: TPOB <tttpob@outlook.com>; Author <author@noreply.github.com>
主题: Re: [rmartin16/qbittorrent-api] Is there a way to update trackers(ask tracker for more peers)? (#1)


I think the reannounce torrents endpoint<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqbittorrent%2FqBittorrent%2Fwiki%2FWeb-API-Documentation%23reannounce-torrents&data=02%7C01%7C%7C19165ba69ddc4c7ed70a08d743580192%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637051917563032394&sdata=pINwW7Q573XC5Kb4pPf45n2mieVsrqDtPVLRii%2B2Qm8%3D&reserved=0> provides this.

client = Client(...)
client.torrents_reannounce(hashes='...')

hashes='all' should work.

―
