### ISSUE TITLE
Document which version of qBittorrent API we are up to?

### ISSUE THREAD

**Issue by victorhooi** [rmartin16/qbittorrent-api#11]
I'm curious - do you know which version of the qBittorrent API we are up to please?

https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#changes

For example, we have a RSS refreshItem call - so we're definitely past 2.2.1.

But it's not clear if we support torrents/renameFile, which came in 2.4.0? (There's a rename call, but that's for torrents?)

Would it be worth documenting which version we're up to in the README somewhere?

**Comment by rmartin16** [comment]
good idea. i try to ensure this client supports all released versions of qBittorrent but i can get a little behind. right now, this client supports all released versions of qBittorrent. this includes torrent file renaming via `torrents_rename_file()`.

I'll add something near the top of the README though.
