### ISSUE TITLE
decrease_priority()  simultaneously

### ISSUE THREAD

**Issue by kucingkembar** [rmartin16/qbittorrent-api#131]
sorry for my bad English and this is very basic,
I have this part code:
```
    for torrent in qbt_client.torrents_info():
        if str(torrent.state) == 'stalledDL':
            print(torrent.name,"priority is reduced")
            torrent.decrease_priority()
```
my problem is: when 2 or more queues are "sequentially", they stacks,
how to select multiple torrents, and decrease_priority them together at once?
thank you, have a nice day

**Comment by rmartin16** [comment]
Let me know if this does not answer your question.

```python
# first, get the hashes for all torrents with state == stalled downloading
hashes = [t.hash for t in qbt_client.torrents_info(status_filter="stalled_downloading")]
# Then, ask qBittorrent to decrease priority for all of those torrents
qbt_client.torrents_decrease_priority(torrent_hashes=hashes)
```

**Comment by kucingkembar** [comment]
thank you for quick reply,
the code is work,
I will study it
thank you again for the hard work, you can close it
