### ISSUE TITLE
`torrents_info` argument `tag` does not filter by tag

### ISSUE THREAD

**Issue by lindenmj** [rmartin16/qbittorrent-api#134]
Running a script on Python 3.8.10, Ubuntu 20.04.5 LTS, and latest qbittorrent-api package. When using the `torrents_info` method and supplying an argument for `tag`, the JSON returned contains all the torrents. The results are not filtered by the tag in the argument.

```
import qbittorrentapi
import json

qbt_client = qbittorrentapi.Client(host=XXX, port=XXX, username=XXX, password=XXX, REQUESTS_ARGS={"auth": ("XXX", "XXX")})
qbt_client.auth_log_in()

torrentinfoJSON = qbt_client.torrents_info(tag="MyTag")

for torrentinfo in torrentinfoJSON:
    sum=sum + torrentinfo.ratio
    x=x+1

if x > 0:    
    avg = sum/x

print(str(x) + "torrents in MyTag = " + str(avg))
qbt_client.auth_log_out()
```

**Comment by rmartin16** [comment]
Which version of qBittorrent are you using? `tag` wasn't added to `torrents/info` until `v4.4.0`.

**Comment by lindenmj** [comment]
Good call, I'm still on 4.3.9.
