### ISSUE TITLE
`qbittorrentapi.Client.torrents_info().content_path` no longer exists?

### ISSUE THREAD

**Issue by donnie58744** [rmartin16/qbittorrent-api#140]
Was this removed or was this method moved somewhere else?

**Comment by rmartin16** [comment]
hmm....I don't remember a `torrent` method called `client_path`....what is it supposed to do?

**Comment by donnie58744** [comment]
> hmm....I don't remember a `torrent` method called `client_path`....what is it supposed to do?

shoot i ment qbittorrentapi.Client.torrents_info()

**Comment by rmartin16** [comment]
ahhh, so, the key/value pairs returned from `Client.torrents_info()` is [controlled](https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/torrentscontroller.cpp#L264) by qBittorrent. That said, `client_path` still doesn't look particularly familiar to me.

Do you know the most recent version of qBittorrent this was being returned?

**Comment by rmartin16** [comment]
All the keys returned for `torrents_info()` are detailed [here](https://github.com/qbittorrent/qBittorrent/blob/v4_5_x/src/webui/api/serialize/serialize_torrent.h).

Maybe youre thinking of `content_path`...?

**Comment by donnie58744** [comment]
> All the keys returned for `torrents_info()` are detailed [here](https://github.com/qbittorrent/qBittorrent/blob/v4_5_x/src/webui/api/serialize/serialize_torrent.h).
> 
> Maybe youre thinking of `content_path`...?

jeez i keep misspelling, i did mean content_path. I did look into the source code and saw the return values, my codebase was working with a qBitorrent verison sometime before 4.2.0, i just cant remember the exact verison

**Comment by donnie58744** [comment]
> ahhh, so, the key/value pairs returned from `Client.torrents_info()` is [controlled](https://github.com/qbittorrent/qBittorrent/blob/master/src/webui/api/torrentscontroller.cpp#L264) by qBittorrent. That said, `client_path` still doesn't look particularly familiar to me.
> 
> Do you know the most recent version of qBittorrent this was being returned?

the error im getting is `AttributeError: 'TorrentDictionary' instance has no attribute 'content_path'`

**Comment by rmartin16** [comment]
I'm not sure then. I just tested on v4.5.0 and I see `content_path` in the response. It may be possible that it isn't returned if the torrent has started yet or something....but the qBittorrent code suggests it'll always be returned.

**Comment by donnie58744** [comment]
> I'm not sure then. I just tested on v4.5.0 and I see `content_path` in the response. It may be possible that it isn't returned if the torrent has started yet or something....but the qBittorrent code suggests it'll always be returned.

im still getting `AttributeError: 'TorrentDictionary' instance has no attribute 'content_path'` even when a torrent is seeding. Its very strange seeing as i can retrieve all other attributes, dlspeed, name, etc...

**Comment by rmartin16** [comment]
Before qBittorrent v4.2.0, it doesn't look like `content_path` was supported; I think it was added in v4.3.0 or after. Either way, if you're getting something back from `torrents_info()` will return whatever is returned from qBittorrent.

You can enable debug logging to see more details about the raw communication with qBittorrent.

This is one way to do that:
```python
import logging

logging.basicConfig(
     level=logging.DEBUG, 
     format='%(asctime)s %(levelname)s %(module)s %(funcName)s %(message)s',
     datefmt='%H:%M:%S'
 )
```

**Comment by donnie58744** [comment]
> Before qBittorrent v4.2.0, it doesn't look like `content_path` was supported; I think it was added in v4.3.0 or after. Either way, `torrents_info()` will return whatever is returned from qBittorrent.
> 
> You can enable debug logging to see more details about the raw communication with qBittorrent.
> 
> This is one way to do that:
> 
> ```python
> import logging
> 
> logging.basicConfig(
>      level=logging.DEBUG, 
>      format='%(asctime)s %(levelname)s %(module)s %(funcName)s %(message)s',
>      datefmt='%H:%M:%S'
>  )
> ```

hmmm alrighty something on my end maybe, ill probably just make the save path relate to the torrent name so the program can just find it that way. But thanks for the quick replys and help 👍
