### ISSUE TITLE
Process left behind when preferences are set

### ISSUE THREAD

**Issue by irisfield** [rmartin16/qbittorrent-api#142]
qbittorrent-api leaves behind a `QThread` process every time the preferences are set for every new client. At first I thought this was happening because I was not logging out using `auth_log_out()`, but nothing changed even after logging out.

```sh
$ pip show qbittorrent-api
Name: qbittorrent-api
Version: 2022.11.40
[...]
```

# Steps to reproduce
1. Launch the daemon (if it is not already running)
```sh
qbittorrent-nox --daemon
```
2. Open an interactive process viewer (`htop`) in a separate window and monitor `qbittorrent-nox` processes
3. Run the following Python script and observe `QThread` processes spawn
```python
from qbittorrentapi import Client

for _ in range(10):
    c = Client(host="localhost:8080", username="admin", password="adminadmin")
    c.application.preferences = {"max_ratio": 2.0}
    # c.app_set_preferences({"max_ratio": 2.0})
```
**Before**
![image](https://user-images.githubusercontent.com/101373246/216851353-d626e616-3677-496c-9fe8-d50f5cca469a.png)

**After**
![image](https://user-images.githubusercontent.com/101373246/216851397-3fb1a785-d0fb-4d6b-b934-3ec63b617bab.png)

# Expectation
Expected `QThread` to properly terminate after the connection ends.

**Comment by rmartin16** [comment]
Which version of `qBittorrent` are you using?

**Comment by irisfield** [comment]
```sh
$ qbittorrent-nox -v
qBittorrent v4.5.0

$ qbittorrent -v
qBittorrent v4.5.0
```

**Comment by rmartin16** [comment]
Ok. I don't think there's anything I can do, unfortunately. This client simply sends HTTP requests to qBittorrent's web server. If they're leaving threads orphaned, they'll probably need to take some action to clean them up.

Would you be willing to report this to them at [qbittorrent/qBittorent](https://github.com/qbittorrent/qbittorrent)?

**Comment by irisfield** [comment]
I understand. I will open a issue at their repo. Just for reference, were you able to reproduce the problem?

**Comment by rmartin16** [comment]
I tried with my local installation but I didn't see a similar build up of threads. I use the linuxserver.io docker image that they occasionally rebuild from the latest version of v4.5.0. So, it may be possible they've already resolved this....or something else is going on.

**Comment by irisfield** [comment]
I tried reinstalling `qbittorrent-nox`, deleting my config, and local data. No idea what was going on, but It fixed the problem.

The following code properly terminates the `QThread` processes.

```python
from qbittorrentapi import Client

for _ in range(10):
    c = Client(host="localhost:8080", username="admin", password="adminadmin")
    c.application.preferences = {"max_ratio": 2.0}
    c.auth_log_out()
```
