### ISSUE TITLE
`torrents_export` returns None

### ISSUE THREAD

**Issue by mchobbylong** [rmartin16/qbittorrent-api#146]
- qBittorrent version: 4.3.9
- Web API version: 2.8.2

Calling method `torrents_export(hash)` does not return bytes of the .torrent file, but only `None`. 

What's odd for me is that I cannot find the corresponding web api in official wiki. Does it mean this method is deprecated?

**Comment by rmartin16** [comment]
It's actually the other way around; `torrents/export` was [introduced](https://github.com/qbittorrent/qBittorrent/pull/16968) in qBittorrent v4.5.0.

Additionally, if you'd like to be warned when an API endpoint isn't avaiable, you can [enable them](https://qbittorrent-api.readthedocs.io/en/latest/behavior%26configuration.html#unimplemented-api-endpoints) when you initialize the `Client`.

**Comment by mchobbylong** [comment]
Thanks for your quick response! That explains, and I am closing the issue.

@rmartin16 Another question though: I retrieved API schema through the [official GitHub wiki](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)), and there are no api versions > 2.8.3. Is there other sites to check the full schema?

**Comment by rmartin16** [comment]
> @rmartin16 Another question though: I retrieved API schema through the [official GitHub wiki](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)), and there are no api versions > 2.8.3. Is there other sites to check the full schema?

Not that I know of, unfortunately; they try to keep it up to date....but it can lag behind. The [API reference](https://qbittorrent-api.readthedocs.io/en/latest/api.html) for this Client, though, contains the all implemented endpoints (which should be all of them).
