### ISSUE TITLE
Build docs with sphinx-build is broken

### ISSUE THREAD

**Issue by fabricionaweb** [rmartin16/qbittorrent-api#165]
### Describe the bug

In the change d950c1bb62dca8e039fddb016ee89f2e63e7e252 the project have been moved to `src/qbittorrentapi` folder but the sphinix still try to import from `qbittorrentapi` and it breaks

```
Warning, treated as error:
autodoc: failed to import class 'app.AppAPIMixIn' from module 'qbittorrentapi'; the following exception was raised:
No module named 'qbittorrentapi'
```

### Steps to reproduce

1. `sphinx-build -W -b man docs/source docs/build`

### Expected behavior

To build without break.

### Environment

- Operating System: Alpine 
- Python version: 3.11.3
- Software versions:
  - qbittorrent-api: 2023.4.45

### Additional context

I was able to fix it by adding `src` to the syspath in the [docs/source/config.py:19](../blob/main/docs/source/conf.py#L19) to something like this:

```python
sys.path.insert(0, os.path.join(base_path, "src"))
```

Not sure it is the best solution, but its my 2cents :)

**Comment by rmartin16** [comment]
Good timing; I was actually just updating docs building.

I always build the docs with an editable install of `qbittorrent-api`; so, I never hit this. But the `base_path` is already being inserted in to `sys.path`, so no reason not to update that to your recommendation.

Thanks for letting me know.
