### ISSUE TITLE
Tags api

### ISSUE THREAD

**Issue by neronmoon** [rmartin16/qbittorrent-api#2]
Hey! Thanks for cool lib!

I've noticed, that you've not implemented tags api: https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#add-torrent-tags

Is there some hope to get this implemented any time soon?

**Comment by neronmoon** [comment]
Hm, seems like it's done, but you have to push new version to pypi

**Comment by rmartin16** [comment]
yeah...i was waiting for the release of qBittorrent v4.2.0....which appears to have happened recently.

I'll work on getting PyPi updated.

In the interim, you can technically install the master branch version with tag support now:

`pip install git+https://github.com/rmartin16/qbittorrent-api.git#egg=qbittorrent-api`

**Comment by rmartin16** [comment]
got pypi updated. i did notice awkward handling around trying to use commas in a tag name...just fyi.
