### ISSUE TITLE
Implement add torrent from bytes

### ISSUE THREAD

**Issue by modbender** [rmartin16/qbittorrent-api#23]
As I have seen in https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/torrents.py#L618, we can pass only string/ list of strings (path/paths) to `torrents_add(torrent_files=)`, could you make it so that we can pass the bytes directly.

I am creating a python code where it downloads .torrent file using requests and directly start downloading the content by passing the response bytes. I could do this before with another package I was using `python-qBitorrent`, now I could save the file and then pass the path, but my aim is not to keep the .torrent file.

An example that I was using with `python-qBitorrent` is:
```python
data = requests.get('url_to_torrentfile.torrent')
qb.download_from_file(data.content)
```

Now I see 2 approaches that can be implemented
1. Maybe create another parameter for `torrents_add` something like `torrents_bytes` that takes 1 or list of bytes
2. Let the users directly pass `open('filepath')` to `torrent_files`, 1 or list of them. Like how it's done in this:
https://github.com/v1k45/python-qBittorrent/blob/master/qbittorrent/client.py#L363
https://github.com/v1k45/python-qBittorrent#downloading-torrents

As I see it 2nd approach is the easiest.

**Comment by rmartin16** [comment]
@modbender, please take a look at #25 if you get a chance. that should add this support. i'll probably merge it tomorrow.

```bash
pip install git+https://github.com/rmartin16/qbittorrent-api.git@cef20226f9ca08931e6611f8a486c99f03568853
```

**Comment by modbender** [comment]
That worked like a charm, thank you 👍
