### ISSUE TITLE
Hash v1 vs v2 surprising behavior

### ISSUE THREAD

**Issue by bland328** [rmartin16/qbittorrent-api#237]
### Describe the bug

When dealing with a torrent that has both `infohash_v1` and `infohash_v2` values, the `torrent.hash` property returns the `infohash_v2` value, but truncated to 40 characters.

Perhaps this is intentional, but I'm guessing it is not.

### Steps to reproduce

See above.

### Expected behavior

I don't really have an opinion on whether `torrent.hash` should provide the v1 or v2 hash, but it seems to me it should not provide a truncated v2 hash. Unless, of course, there's a great reason for that behavior that's simply above my pay grade :)

### Environment

- Operating System: Linux
- Python version: 3.11
- Software versions:
  - qBittorrent: v4.5.3
  - qbittorrent-api: 2023.6.49

**Comment by rmartin16** [comment]
This is apparently by design in qBittorrent. For v1-only torrents, the hash is the 160 byte sha1 hash. For hybrid or v2-only torrents, the hash is the first 160 bytes (i.e. first 40 numbers) of the v2 sha256 hash. They call this the Torrent ID. This can make things a little confusing....for instance, this Torrent ID must be used to identify torrents in API calls, such as `client.torrents_info(torrent_hashes="...")`.

**Comment by bland328** [comment]
Ah! Thanks very much for the explanation.

Though one point of confusion--does this mean that the `hash` property (perhaps better thought of as "id") may have one value immediately after a torrent is added via magnet link, then a second new value after metadata becomes available and a V2 hash becomes known?

If so, that explains why my automation becomes confused by torrents with V2 hashes.

**Comment by rmartin16** [comment]
> does this mean that the `hash` property (perhaps better thought of as "id") may have one value immediately after a torrent is added via magnet link, then a second new value after metadata becomes available and a V2 hash becomes known?

hmm...if the `hash` value is changing, I would report that to the qBittorrent team. While the concept of this Torrent ID may already be dubious, if its value from qBittorrent is changing, that seems like a bug. I'm not familiar, though, with how they derive the Torrent ID before and after the metadata download finishes.

**Comment by bland328** [comment]
Thanks. I'm 99% certain the value does change in that situation. I've added a trap to detect the situation, and will report it to the qBittorrent team once I've confirmed it.
