### ISSUE TITLE
Get torrent object on adding torrent

### ISSUE THREAD

**Issue by modbender** [rmartin16/qbittorrent-api#29]
Is it possible that you can make it so that when `torrents_add` is called it returns torrent object? Supposedly I have a torrent magnet url and no other info about it, and the hash is tagged-info-hash which is not info-hash, 

Example magnet link: 
`magnet:?xt=urn:btih:GQMKCY7EZSUS3PDQY7FL23X2AM763ESE&tr=udp://tracker.coppersurfer.tk:6969/announce`
I thought assuming and using `GQMKCY7EZSUS3PDQY7FL23X2AM763ESE` as info hash was enough, but after I added the magnet url the info hash came out as `3418a163e4cca92dbc70c7cabd6efa033fed9244` and then I learnt that there are 2 types of hashes from here: https://stackoverflow.com/questions/61640538/obtaining-metadata-from-magnetlink-infohash

In this scenario after adding the torrent I don't know how to get the torrent object, because `torrents_add` returns `Ok.` and the torrent is then lost (No way to find which is the added torrent)

**Comment by rmartin16** [comment]
i've thought about this as well....i really wish qBittorrent returned something more meaningful than "ok." or "fails."

that said, this API client doesn't have any more information about which torrent is being added to qBittorrent than you would....i mean, this client literally just sends URLs or the binary content of files to qBittorrent......the qBittorrent app does all the work to figure out what torrent actually needs to be added and downloaded.

maybe something is possible....i'll think about it some more later.

**Comment by rmartin16** [comment]
Existing enhancement request: qbittorrent/qbittorrent#4879

**Comment by modbender** [comment]
Ok leaving that aside do you know any method to get the info hash `3418a163e4cca92dbc70c7cabd6efa033fed9244` from `GQMKCY7EZSUS3PDQY7FL23X2AM763ESE`?

**Comment by modbender** [comment]
I went to python discord and asked the question surprisingly I got the right answer:
Here is what I'm using to get info hash from magnet url.
```
def get_magnet_hash(magnet_url):
    extract = magnet_url[magnet_url.find("btih:") + 5:magnet_url.find("&")]
    if len(extract) != 40:
        return base64.b16encode(base64.b32decode(extract)).lower().decode('utf8')
    return extract
```

**Comment by rmartin16** [comment]
nice. i was poking around but the hashing algorithm wasn't entirely obvious....it does look like magnet links can be quite varied and support all kinds of specifications...as long as they're just `btih` magnets....i'd expect that to work great.
