### ISSUE TITLE
torrents_add(torrent_files=raw_bytes) does not work in Python 3

### ISSUE THREAD

**Issue by dkbarn** [rmartin16/qbittorrent-api#34]
The torrents_add() function is documented as accepting a byte string as one of the possible types for the torrent_files argument, but this does not work in Python 3.

At line 647, the if statement is skipped for type 'bytes', and user_files does not get wrapped in a list
https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/torrents.py#L647

At line 651, type 'bytes' is not a Mapping, so we end up with the "else" statement which creates a massive dictionary due to enumerating over every byte in the byte string.
https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/torrents.py#L651

I think the bug is on line 647, where checking against six.string_types (which resolves to only "str" in Python 3), should instead check against "unicode", "str", and "bytes". For example:

isinstance(user_files, (bytes, six.text_type))

**Comment by rmartin16** [comment]
wow....guess i completely overlooked this test case. thanks for letting me know. i should be able to push out a fix in the next few days.

**Comment by rmartin16** [comment]
i'm not super familiar with six and python 2.....but in case you have any insight...

instead of only checking for `six.string_types`, i'm going to update it to check for `(six.string_types, six.binary_type)`.

for python 3, that'll identify `str` and `bytes`.....and for python 2, that'll identify `str`, `unicode`, and `bytes`.

**Comment by dkbarn** [comment]
You shouldn't need to check against str and bytes separately in Python 2, because the bytes literal is an alias for str from Python 2.6+.

isinstance(user_files, (bytes, six.text_type)) will cover all the bases

**Comment by rmartin16** [comment]
ahh ok, yeah, that makes more sense to me now. i had to realize that `str` and `bytes` are literally the same thing in python 2. thanks.
