### ISSUE TITLE
torrents_count() not a function in API

### ISSUE THREAD

**Issue by ddean6232** [rmartin16/qbittorrent-api#381]
### Describe the bug

Can get api to report on number of torrents with torrents_count()

### Steps to reproduce

Everything else works but I must to missing something on the torrent_count() function.

```from bs4 import BeautifulSoup
import qbittorrentapi

# Assuming the qBittorrent web UI is at the default location on localhost port 8080.
# Replace 'user' and 'password' with the correct credentials.
qbt_client = qbittorrentapi.Client(host='http://192.168.0.5:8080', username='admin', password='adminadmin')

# Log in to qBittorrent Web UI
try:
    qbt_client.auth_log_in()
except qbittorrentapi.LoginFailed as e:
    print(f"Login to qBittorrent Web UI failed: {e}")
    exit()

# Function to add a list of magnet URLs to qBittorrent
def add_magnet_links(magnet_links):
    for magnet_link in magnet_links:
        try:
            # Add magnet link to qBittorrent
            qbt_client.torrents_add(urls=magnet_link, is_paused=True)
            print(f'Successfully added magnet link to qBittorrent: {magnet_link}')
        except Exception as e:
            print(f'Failed to add magnet link to qBittorrent: {e}')

# Read the input.txt file
with open('input.txt', 'r') as file:
    html_content = file.read()

# Parse the HTML to find the <a href> tags with magnet URLs
soup = BeautifulSoup(html_content, 'html.parser')
magnet_links = [link.get('href') for link in soup.find_all('a', href=True) if link.get('href').startswith('magnet:')]

# Add the magnet URLs to qBittorrent
add_magnet_links(magnet_links)
count = qbt_client.torrents_count()
print(count)

### Expected behavior

number of torrents as integer

### Screenshots

_No response_

### Environment

qBittorrent: v4.6.0
qBittorrent Web API: 2.9.2
bitness: 64
boost: 1.82.0
libtorrent: 2.0.9.0
openssl: 3.1.4
qt: 6.6.0
zlib: 1.3


### Additional context

_No response_

**Comment by rmartin16** [comment]
It is [implemented](https://github.com/rmartin16/qbittorrent-api/blob/a51398ea531cbe2dfbaad30a21701fc164178227/src/qbittorrentapi/torrents.py#L425)...I just haven't cut a new release yet. I'm waiting on qBittorrent to make a new release first.

You can install direct from GitHub with `pip install git+https://github.com/rmartin16/qbittorrent-api`.

All that said, `torrents/count` exists in Web API v2.9.3....which hasn't been released by the qBittorrent team AFAIK. I could be wrong....I don't quite follow how they push out changes on their `x4_6_x` branch prior to cutting actually new releases. They are certainly building up to a v4.6.1 release.

**Comment by ddean6232** [comment]
thanks Russell.  Used your code and now no invalid function but always returns 'None'.  I assume that I will have to wait for QBTT to release WebAPI 2.9.3 to get a result.

**Comment by rmartin16** [comment]
You're welcome. Although, keep in mind that if this client doesn't think that an API endpoint exists yet for the qBittorrent host, it doesn't actually send a API request to qBittorrent at all and just returns `None`. You can change this [behavior](https://qbittorrent-api.readthedocs.io/en/latest/behavior%26configuration.html#unimplemented-api-endpoints) if you want when you instantiate `qbittorrentapi.Client()` to raise an exception instead.

You can use something like this, though, to confirm whether the `torrents/count` endpoint is actually available or not. qBittorrent will return an HTTP 404 when an endpoint doesn't exist.

```bash
QBT_HOST="http://localhost:8080"
QBT_USER="admin"
QBT_PASSWORD="adminadmin"

# log in
SID=$(curl -XPOST "$QBT_HOST/api/v2/auth/login" -F "username=$QBT_USER" -F "password=$QBT_PASSWORD" --silent --cookie-jar - | grep -F "HttpOnly" | awk '{print $NF}')

# hit torrents/count endpoint
curl -v -XPOST "$QBT_HOST/api/v2/torrents/count" --cookie "SID=$SID"
```

**Comment by ddean6232** [comment]
well I guess I'm a typical programmer... doesn't read the docs.  Thanks again and I will implement your suggestions
