### ISSUE TITLE
can this software control Bittorrent Option?

### ISSUE THREAD

**Issue by kucingkembar** [rmartin16/qbittorrent-api#412]
### What is the problem or limitation you are having?

in Option -> Bittorrent ->
there this setting: 
<html><body>
<legend><label for="queueing_checkbox">Torrent Queueing</label>
        </legend>
        
Maximum active downloads: |  
-- | --
Maximum active uploads: |  
Maximum active torrents:

</body>
</html>
can this software control these setting?

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by rmartin16** [comment]
Yes, the application preferences endpoint.

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-application-preferences

https://qbittorrent-api.readthedocs.io/en/latest/apidoc/app.html#qbittorrentapi.app.AppAPIMixIn.app_set_preferences

**Comment by kucingkembar** [comment]
thank you
