### ISSUE TITLE
client.torrents.info.paused() is returning completed torrents?

### ISSUE THREAD

**Issue by dantebarba** [rmartin16/qbittorrent-api#43]
Hi!.

First I would like to thank you for your excellent work on this api-client. I'm currently using it to handle my qbittorrent queue. Anyway I stumbled into a small hiccup, which is when retrieving paused torrents with the statement `qbt_client.torrents.info.paused() ` the api returns torrents that are in 'Completed' status too. Is this normal behaviour or it's a bug?

**Version:** 

api: `qbittorrent-api==2020.12.15`
qbt: 4.3.1
python: python:3.8 image from Dockerhub

Regards

**Comment by rmartin16** [comment]
Yeah....this statuses have led to confusion for me too. qBittorrent is more or less mapping internal statuses to these more abstracted statuses....and the results can be confusing.

I've tried to abstract (or perhaps even just reimplement) qBittorrent's torrent states in [`TorrentStates`](https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/definitions.py#L29). That reveals the mapping between internal and external torrent state.

Here, you can see their [implementation of the mapping](https://github.com/qbittorrent/qBittorrent/blob/15f1fdddd991126829714f1a5715d38d0accf8e7/src/base/torrentfilter.cpp#L156).

If you follow `torrent->isPaused()` far enough, you find that [paused really means stopped internally](https://github.com/qbittorrent/qBittorrent/blob/15f1fdddd991126829714f1a5715d38d0accf8e7/src/base/bittorrent/torrentimpl.cpp#L634).

This `swtich` shows the [entire mapping](https://github.com/qbittorrent/qBittorrent/blob/e60b91b5e28dd643d2ef39e845392454d8578ffb/src/webui/www/private/scripts/dynamicTable.js#L869)....at least as it manifests in the Web UI.

At any rate, as far as qBittorrent appears to be concerned, "stopped" torrents are considered "paused"....or vice versa...however you want to look at it.

Let me know if that didn't answer you question or if you have follow up. Thanks.

**Comment by rmartin16** [comment]
And maybe more directly....the internal qBittorrent torrent state of `pausedDL` is considered both "Paused" and "Completed"....so, your observation may be more that a single torrent have may multiple of these more abstracted states....

**Comment by dantebarba** [comment]
Ok that was way more complex than expected. I will just add an "if progress < 100" to filter the results for now. Thanks for the complete answer.
