### ISSUE TITLE
Pool connections

### ISSUE THREAD

**Issue by anasty17** [rmartin16/qbittorrent-api#458]
### What is the problem or limitation you are having?

While using the same session for concurrent tasks, pool connection error raised

### Describe the solution you'd like

What about increasing the pool_connections and pool_maxsize in httpadapter? Both to 100

Also enabling pool_block will queue the requests

So i don't need to create new client and logout again and again for each task

### Describe alternatives you've considered

Adding async support to use httpx would take too much time, so i will not ask for it :)

### Additional context

Thank You

**Comment by rmartin16** [comment]
Thanks for letting me know. What about adding an argument for [`Client`](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/client.html) to pass arbitrary configuration for `HTTPAdapter` similar to how `REQUEST_ARGS` allows configuring each `requests.request()` call?

**Comment by anasty17** [comment]
> Thanks for letting me know. What about adding an argument for [`Client`](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/client.html) to pass arbitrary configuration for `HTTPAdapter` similar to how `REQUEST_ARGS` allows configuring each `requests.request()` call?

This would be much better 
Thanks a lot
