### ISSUE TITLE
why use lambda ? 

### ISSUE THREAD

**Issue by QuantumNovice** [rmartin16/qbittorrent-api#49]
https://github.com/rmartin16/qbittorrent-api/blob/d3c6c54cc8497e4746f7eb791baaf8fb880c6f15/qbittorrentapi/transfer.py#L170-L171
wouldn't this suffice the use case here?
```python
is_enabled = self.transfer_speed_limits_mode() == "1" 
```

**Comment by rmartin16** [comment]
ohh....it's an attempt at an optimization. calling `self.transfer_speed_limits_mode()` will make an API call to qBittorrent and i didn't want that incurred unless the user explicitly set `intended_state`.
