### ISSUE TITLE
Version Checking Requires Too Much Cognitive Overhead To Read

### ISSUE THREAD

**Issue by rmartin16** [rmartin16/qbittorrent-api#52]
Since a lot of things change in the qBittorrent Web API, there is a lot of qBittorrent version comparisons to see which features are available.

Like this:
```python
if (
    content_layout is None
    and is_root_folder is not None
    and self._is_version_less_than("2.7", api_version, lteq=True)
):
    content_layout = "Original" if is_root_folder else "NoSubfolder"
    is_root_folder = None
```

Every time I read this, I have to really think about what's happening......create wrappers to make this more intuitive.

**Comment by C84186** [comment]
You could maybe make a `Version` class which compares with `Version`s & `str`s (Chances are someone has already invented a semver class wrapper) and just use 

self.version <= "2.7"
