### ISSUE TITLE
Impossible to rename torrent with spaces

### ISSUE THREAD

**Issue by Forden** [rmartin16/qbittorrent-api#58]
When using `torrents_rename("Hello World")` torrent will get name "Hello+World", but web interface allows to rename torrent correctly. Could you fix it please?
Using qbittorrent-api version 2021.5.22

**Comment by rmartin16** [comment]
Which version of qBittorrent are you using? I think this was fixed by qBittorrent/qbittorrent#10607

**Comment by Forden** [comment]
Oh, i was using qBittorrent 4.1.5. After updating to latest (4.3.5) this problem has gone. Thx for fast reply!
