### ISSUE TITLE
Client method to get statistics

### ISSUE THREAD

**Issue by Seluj78** [rmartin16/qbittorrent-api#64]
Hey !

I've searched the docs and didn't find a route to get statistics for the client.

For example, current down and up speed, total downloaded, uploaded etc... So I can put those in a chart :) Is this something that you plan on adding ? Or am I blind 🤣

**Comment by rmartin16** [comment]
This client should implement every endpoint that qBittorrent makes available in each version.

I think one of the [transfer API endpoints](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#transfer-info) should provide this information.

**Comment by Seluj78** [comment]
Ok so this should cover the current speed and stuff but what about statistics ? The one that shows total download and upload for global and session ? I didn't find it in their doc :/

**Comment by rmartin16** [comment]
Try the `server_state` node of the return value for `qbt_client.sync.maindata`....that should do it....although, their wiki doesn't really show that right now.

**Comment by Seluj78** [comment]
Amazing ! Thanks a lot
