### ISSUE TITLE
torrents_rename_folder method has no effect

### ISSUE THREAD

**Issue by apenasrr** [rmartin16/qbittorrent-api#71]
In qBitorrent v4.2.5,
when using the [torrents_rename_folder](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_rename_folder)  method to rename a folder that is the content of a torrent, no error is raised, nor does it generate any rename effect.

I try to change the folder of a torrent's internal content, similar to what can be done using the qbittorrent application by going to the 'Content' tab, selecting a folder, hitting the 'F2' button and renaming it.

**Comment by rmartin16** [comment]
A few questions to get us started:

Which version of qBittorrent are you trying this with?

Can you also please provide an example of the python statement you're using to call `torrents_rename_folder`?

**Comment by apenasrr** [comment]
I tried for qbittorrent 4.2.5.
I recently tried it on qbit 4.3.9 , and everything worked fine.

I apologize for opening the question before using a recent version of the app.
If I may suggest this, raising an error in case of using a method not supported by the application would be preferable instead of returning None with no effect.

I am very grateful for your project. Happy Holidays.

**Comment by rmartin16** [comment]
> I apologize for opening the question before using a recent version of the app.

No worries :)

> If I may suggest this, raising an error in case of using a method not supported by the application would be preferable instead of returning None with no effect.

Yeah....this was an early design decision...I am still not sure if defaulting to returning `None` over an `Exception` was the best idea...nonetheless, you can get Exceptions back by instantiating `Client` like below:

```python
qbt_client = qbittorrentapi.Client(
    host='localhost',
    port=8080,
    username='admin',
    password='adminadmin',
    RAISE_NOTIMPLEMENTEDERROR_FOR_UNIMPLEMENTED_API_ENDPOINTS=True
)
```

Happy holidays to you as well.... feel free to let me know if you run in to other issues :)
