### ISSUE TITLE
[Feature Request]: Get supported version

### ISSUE THREAD

**Issue by bobokun** [rmartin16/qbittorrent-api#75]
Thank you for building and maintaining this API! 

With the new release of v4.4 breaking the web API, would it be possible to add to this a supported version variable somewhere so I know what version of qbittorrent this currently supports? Right now the other alternative option is to look at the README page and filter out `Currently supports up to qBittorrent v4.3.9 (Web API v2.8.2) released on Oct 31, 2021.`

**Comment by rmartin16** [comment]
> Thank you for building and maintaining this API!

You're welcome :)

> add [...] a supported version variable somewhere

That's seems reasonable. I should be able to add something to #60. To avoid users having to do version parsing, do you have a preference for maybe a method that returns a list of supported qBittorrent versions? or maybe just a method that takes a stringified version and just returns a bool for whether it's supported? I'm concerned that just returning the version as a raw string will lead to bad/error-prone comparisons of raw version strings....

**Comment by bobokun** [comment]
Actually thinking about it maybe you can it as an exception? When instantiating the client and performing a `qbt_client.auth_log_in()` , if the login was successful you can get the version from `qbt_client.app.version` and throw an Exception if it's greater than the current supported version.

**Comment by rmartin16** [comment]
That seems mostly reasonable, too. Although, I think that's too heavy-handed to apply by default; for the most part, this client will continue to function properly even if no one makes updates to it for a while....and I don't want to make users update their version of this client if they don't need functionality in newer versions.

That said, I don't see why this couldn't be included as one of the [more esoteric configuration options](https://github.com/rmartin16/qbittorrent-api/blob/master/qbittorrentapi/request.py#L93)....maybe something like `RAISE_UNSUPPORTEDVERSIONERROR_FOR_UNSUPPORTED_QBITTORRENT_VERSIONS`....or something....
