### ISSUE TITLE
Confused about paths in torrents_rename_folder

### ISSUE THREAD

**Issue by farmwald** [rmartin16/qbittorrent-api#79]
I'm trying to rename a torrent folder using the API..
I use an absolute path for both the new and old paths (in linux, haven't tried windows), and I get an error message that absolute paths are not allowed.
So what are the paths supposed to be relative to? I can't find any examples or explanations in the documentation.
This should be more of a forum question, so where is the best place to ask questions like this?

**Comment by rmartin16** [comment]
Hello @farmwald,
Here's an example with a dummy torrent I just made.

**Files in torrent**
![image](https://user-images.githubusercontent.com/387848/151591460-78f24b73-ee80-4062-bab0-3625c5f436a5.png)
```python
for file in client.torrents_files("35ea45daf588289aba0dee455eff33246db58d4b"):
     pprint(dict(file))

{'availability': 0,
 'id': 0,
 'index': 0,
 'is_seed': False,
 'name': 'rootdir/dir1/file1',
 'piece_range': [0, 0],
 'priority': 1,
 'progress': 0,
 'size': 6}
{'availability': 0,
 'id': 1,
 'index': 1,
 'name': 'rootdir/dir2/file2',
 'piece_range': [0, 0],
 'priority': 1,
 'progress': 0,
 'size': 6}
```

**Rename `dir1` folder to `dir1new`**
```python
client.torrents_rename_folder(old_path="rootdir/dir1", new_path="rootdir/dir1new", torrent_hash="35ea45daf588289aba0dee455eff33246db58d4b")
```

**Updated Files in torrent**
![image](https://user-images.githubusercontent.com/387848/151592218-262a6b9d-8391-408c-a5c1-98c02d432f24.png)
```python
for file in client.torrents_files("35ea45daf588289aba0dee455eff33246db58d4b"):
     pprint(dict(file))

{'availability': 0,
 'id': 0,
 'index': 0,
 'is_seed': False,
 'name': 'rootdir/dir1new/file1',
 'piece_range': [0, 0],
 'priority': 1,
 'progress': 0,
 'size': 6}
{'availability': 0,
 'id': 1,
 'index': 1,
 'name': 'rootdir/dir2/file2',
 'piece_range': [0, 0],
 'priority': 1,
 'progress': 0,
 'size': 6}
```

Hope that helps. Let me know if you run into more issues.

**Comment by farmwald** [comment]
This is very helpful, but I'm still having problems with two different cases.

In both cases, I'm trying to rename the "top" file or directory, i.e. "rootdir" in your example.
In one case, rootdir is actually a directory, and I want to change its name (to match a modified torrent name). It sort of works,
in that qbittorrent changes the name under content in the qbittorrent gui, but doesn't rename the actual folder. This leaves the torrent in an errored state. The old dirname contains non-ascii characters which may be relevant. I can try it with a more standard name.

In the other case, I'm trying to rename a single file at the top level, no directories involved. I've tried both torrent_rename_file and torrent_rename_folder. Both fail for me. rename_file fails complaining about new_path and old_path - I've tried
path=".",, path="", and not adding them (path=None) - all throw errors.
torrent_rename_folder throws an error that no such directory exists.

Thanks for the help.

**Comment by rmartin16** [comment]
Hmm....you should be able to rename the top directory of the torrent with the `torrents_rename_folder` command; that even changed the directory on the disk for me. It's possible qBittorrent is encountering some sort of error; perhaps their log would capture that.

Further, though, I also will usually do things in qBittorrent's WebUI to understand how they use the API for different tasks. You can open up the dev tools with F12 or some menu, select the Network tab and there you can see the API calls being made to qBittorrent when you rename things. That may help clarify what's going wrong as well.

You can even get verbose logging out of this client if you initialize it like this:
```python
import logging
logging.basicConfig(level=logging.DEBUG, format='[%(asctime)s] {%(name)s:%(lineno)d} %(levelname)s - %(message)s')

import qbittorrentapi
client = qbittorrentapi.Client(host='localhost:8080', username="admin", password="adminadmin", VERBOSE_RESPONSE_LOGGING=True)
```

The `torrents_rename_file` command will allow you rename files. I used this command for a single file torrent:
```python
client.torrents_rename_folder(old_path="kubuntu-21.04-desktop-amd64.iso", new_path="new_kubuntu-21.04-desktop-amd64.iso", torrent_hash="d65d07329264aecb2d2be7a6c0e86b6613b2a600")
```

**Comment by rmartin16** [comment]
Another thought is to confirm the version of qBittorrent you're using. Some package managers have quite old versions.

**Comment by farmwald** [comment]
I'm on either 4.4.0 or 4.5.0, depending.
It sounds like the problems are mine, so let me generate some simple test cases and also check the log.

**Comment by farmwald** [comment]
I had a bug - seems to work just fine.
Thanks.

**Comment by rmartin16** [comment]
Good deal; glad you got it worked out.
