### ISSUE TITLE
[Question] get only recently added torrents.

### ISSUE THREAD

**Issue by swannie-eire** [rmartin16/qbittorrent-api#84]
This is a question. Sorry for asking here but not sure where else to. I had a look through the wiki but dont see it so said i would ask or else i missed it.

Currently its not possible to add tags to a torrent when adding them from the webUI manually so I want to write a script which checks the last X recently added torrents and add tags to them depending on the tracker, source and if the torrent is private. I plan to run this once every 30 minutes or so inn a cron job. In my case i have thousands of torrents and dont want to have to check each one when it was added, does it have tags etc.. so am hoping to be able to get n most recently added torrents.

Have you any suggestions on how to do this without getting all torrents and then filtering them.

**Comment by rmartin16** [comment]
The `torrents/info` [endpoint](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list) (or at [RTD](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_info)) provides a few parameters to control how torrents are returned. Notably, `limit` and `sort`.

For instance, this'll return the last 3 added torrents:
```python
client.torrents_info(sort='added_on', limit=3)
```

**Comment by swannie-eire** [comment]
> The `torrents/info` [endpoint](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list) (or at [RTD](https://qbittorrent-api.readthedocs.io/en/latest/apidoc/torrents.html#qbittorrentapi.torrents.TorrentsAPIMixIn.torrents_info)) provides a few parameters to control how torrents are returned. Notably, `limit` and `sort`.
> 
> For instance, this'll return the last 3 added torrents:
> 
> ```python
> client.torrents_info(sort='added_on', limit=3)
> ```
> 
> Additionally, you could include `offset=3`, for instance, to get the next 3 most recently added torrents. Iteratively increasing `offset` by the value of `limit` would allow you to paginate through as many torrents as you like.

Thank you so much. I read the wiki a few times and totally missed that.

Thanks again.
