### ISSUE TITLE
missing getting progress 

### ISSUE THREAD

**Issue by shmizan** [rmartin16/qbittorrent-api#9]
Hi, lovely lib!
I'm trying to query the client for progress of a specific torrent.
right now I don't see any method to get progress as described here:
https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation#get-torrent-contents

moreover, the methods that are available (i.e. top priority) only seem to be available though a torrent instance, that must be be received through iteration on torrent list?
I want to address a specific torrent through its hash, and I can't find a way.

**Comment by rmartin16** [comment]
That link is for an older version of qBittorrent's Web API. Below is a link to the latest version.

https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#get-torrent-contents

Then you can use the `torrents_files()` method to get individual file progress with the torrent hash.

**Comment by shmizan** [comment]
thanks for the quick reply!
sorry, I missed that.  works beautifully.
closing.
