### ISSUE TITLE
Qbittorrent-nox

### ISSUE THREAD

**Issue by anasty17** [rmartin16/qbittorrent-api#94]
Hi, hope everything is well

It's not a bug in your package.

But i don't know what to report for qbitorrent team, maybe if you can understand what the issue so you or me can open issue.

magnet:?xt=urn:btih:ZRV5MMSDGGHSVTFPCQEOWK5MMSD3WT6E&dn=Cavaleiro%20da%20Lua%20S01E06%20WEB-DL%201080p%20DUAL%205.1&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce

With v.4.3.9 this magnet link works normally, the hash will converted to base16. I use this:

hash_ = b16encode(b32decode(str(hash_))).decode()

In the latest version 4.4.3.1 it's not working and i can't pause it. I'm using also tag so I'm trying to get info from tag also nothing.

I add this magnet locally on my phone and have have generated torrent file and it worked on latest version but with different hash.

So if you can understand the issue then I can report to qbittorrent team and thanks in advance.

**Comment by rmartin16** [comment]
I'm not sure I'm following entirely. I can successfully add this torrent on both `v4.3.9` and `v4.4.3.1`....it isn't downloading (and just stays at Metadata Downloading) but it seems to be behaving ok.

What do you mean "its not working"? Any idea how to perhaps reproduce what you're seeing?

**Comment by anasty17** [comment]
It's downloading on 4.3.9 and it have good seeders.
On latest version It's not get paused when i try to pause it.
And it's stay on downloading metadata

**Comment by anasty17** [comment]
![20220717_232316](https://user-images.githubusercontent.com/77075674/179423608-faa3b196-3cd1-46b7-8f1b-44924e94b7d6.jpg)

This one on latest version.


![20220717_232334](https://user-images.githubusercontent.com/77075674/179423620-bdfe75b5-cef2-4548-8052-0254a99ac3c6.jpg)
And this one on v4.3.9

**Comment by anasty17** [comment]
![Screenshot_20220717-232751_Plus](https://user-images.githubusercontent.com/77075674/179423716-9afd7200-9305-4d99-9f22-7a9a26670bc7.jpg)

Now i have added magnet link locally and created torrent file from phone app.

If u see after /cancel there is a gid ... this gid is the first part of hash.

I got this hash from torrent info using tag.

1st hash: cc6bd63243318f2accaf1408eb2bac6487bb4fc4

2nd hash: 21aa46b81de6b905b78536391f8b8cdcc712b8fe

**Comment by rmartin16** [comment]
I think the hash differences may come down different versions of libtorrent being used between qBittorrent `v4.3.9` and `v4.4.3.1`. I think they starting shipping `v4.4+` with libtorrent `v2.0.x` when they were using `v1.2.x` before. You can see the libtorrent version in Help -> About -> Software Used.

This may also explain why the torrent is behaving differently between v4.4.3.1 and v4.3.9.....however, I do not understand bittorrent well enough to even suggest why that might be.....i can confirm the torrent is still just trying to download metadata still...

**Comment by anasty17** [comment]
Okay thanks alot
