### ISSUE TITLE
torrents_setLocation with spaces

### ISSUE THREAD

**Issue by alexxroche** [rmartin16/qbittorrent-api#97]
If the new Location includes spaces in the directory names they are replaced with `+`.
I've tried to escape the spaces or replace them with `\x20` to no avail.

If I use urllib.parse.quote(location) then qbittorren's API doesn't decode that and creates a new path with a literal `%20` replacing the spaces.

The WebUI doesn't have this problem. (`torrents_set_location` does not change location before submitting it as a dict using _post, so I presume this is `from urllib.parse import urljoin` being "helpful" and replacing the spaces with `+` ?)

**Comment by rmartin16** [comment]
Hello @alexxroche ,
Which version of qBittorrent are you using?

I think they should have resolved this with qbittorrent/qBittorrent#10606.

**Comment by rmartin16** [comment]
Let me know if you're still having this problem; I'm interested in replicating it. Especially since `torrents_set_location()` sends the filesystem location via `POST` so I don't think anything should be getting URL encoded...
